### ISSUE TITLE
527K name ?

### ISSUE THREAD

**Issue by Ulrar** [libdyson-wg/ha-dyson#20]
Hi,

Finally got around to migrating to this but I don't see the 527K in the list when doing a manual setup, is it not added here yet ?

Also when selecting another model instead (regular hot+cool) it fails to connect, with no additional information whereas the old integration does connect fine, but is missing the formaldehyde and No2 sensor of course, not quite sure why this may be.

Thanks

**Comment by Ulrar** [comment]
I was able to set it up using the cloud integration, so it is in there, just not sure under what name.
Interestingly it's not pulling the same thing as my PRs on the old integration, it's pulling two indexes instead of VOC and No2, and for the formaldehyde it's just a number with no unit. I remember having to fix that up in the library in one of my PRs, probably the same issue here, from memory I think the sensor class was missing at least

**Comment by dotvezz** [comment]
Getting ahead of myself here: I'm glad you were able to get it up and running! I remember your old PR on shenxn's repo. Unfortunately Dyson decided to be a bunch of jerks and serve us up a naming collision with every E- and K-suffixed model code, which made your perfectly good PR a non-starter. For example, 527K is shared by _two_ similar, yet different, devices: The HP07 "Purifier Hot+Cool" and the HP09 "Purifier Hot+Cool Formaldehyde." Those device can also both be 527E as well, to make things even more fun.

There's more details in [this old PR on libdyson-neon](https://github.com/libdyson-wg/libdyson-neon/pull/7), and in the python comments for the consts [over here](https://github.com/libdyson-wg/libdyson-neon/blob/main/libdyson/const.py#L10C1-L18) if you want to read it and be really frustrated by Dyson's decision to do this.

So `libdyson-neon` and this fork support Formaldehyde models universally through an interview step, rather than by classifying each distinct model with distinct capabilities and native sensors.

> I don't see the 527K in the list when doing a manual setup, is it not added here yet ?

This is also due to the naming collision - right now, we're still using the original libdyson's one-to-one devoce-code/device-name assumptions as set up in const.py. I want to make it more dynamic to allow for shared product codes. 

That might be really easy, but not a high priority since all the K/E devices ship without a wifi/credentials sticker, so the API used by the cloud integration is probably the only way to get the MQTT credentials required to connect to it. But if anyone else can figure out a way, that'd be awesome! (I have a non-Formaldehyde 527K so maybe I can try to figure something out later)

That said, it sounds like you have manual connection credentials already prepared somehow? I'm curious how you got your hands on that! If it turns out manual setup is a reasonable first-choice solution, we can definitely add it.

> Interestingly it's not pulling the same thing as my PRs on the old integration, it's pulling two indexes instead of VOC and No2

Funny enough, that's because the old integration was completely wrong in its assumptions about the data :upside_down_face:. There's a lot of discussion about it in #3 and #4 if you're interested! The short version is this: The sensors from the device itself aren't providing raw data in ppm or μg/m<sup>3</sup> as previously supposed. It's actually just giving an index value that's (far as I can tell) proprietary to Dyson, and without knowing their conversion factors it's not possible to translate to a more meaningful measurement.

> for the formaldehyde it's just a number with no unit. I remember having to fix that up in the library in one of my PRs, probably the same issue here, from memory I think the sensor class was missing at least

We're still trying to figure out the raw data and understand what the base unit (or possible conversion factor) is for Formaldehyde. Weirdly enough, the app displays Formaldehyde (which is a VOC) in mg/m<sup>3</sup>, but for the general VOC sensor, it uses an index value. More discussion in #3 if you'd like to help us figure it out!

**Comment by dotvezz** [comment]
Also since you've raised PRs on shenxn's repo, are you interested in helping reduce the bus factor here and join libdyson-wg so we can have people to actually review/merge PRs and stuff? :smile:

**Comment by Ulrar** [comment]
> Getting ahead of myself here: I'm glad you were able to get it up and running! I remember your old PR on shenxn's repo. Unfortunately Dyson decided to be a bunch of jerks and serve us up a naming collision with every E- and K-suffixed model code, which made your perfectly good PR a non-starter. For example, 527K is shared by _two_ similar, yet different, devices: The HP07 "Purifier Hot+Cool" and the HP09 "Purifier Hot+Cool Formaldehyde." Those devices can also both be 527E as well, to make things even more fun.
> 
> There's more details in [this old PR on libdyson-neon](https://github.com/libdyson-wg/libdyson-neon/pull/7), and in the python comments for the consts [over here](https://github.com/libdyson-wg/libdyson-neon/blob/main/libdyson/const.py#L10C1-L18) if you want to read it and be really frustrated by Dyson's decision to do this.
> 


I did have a suspicion, hard to say with the one fan but I read up on other PRs at the time and it did seem like people were referencing the same product code a lot when talking about different models. That explains it !

> So `libdyson-neon` and this fork support Formaldehyde models universally through an interview step, rather than by classifying each distinct model with distinct capabilities and native sensors.
> 
> > I don't see the 527K in the list when doing a manual setup, is it not added here yet ?
> 
> This is also due to the naming collision - right now, we're still using the original libdyson's one-to-one devoce-code/device-name assumptions as set up in const.py. I want to make it more dynamic to allow for shared product codes.
> 

Right, currently it's mapping everything from that device code assuming it'll be unique, so even though the integration could display as many names as you want in the drop down there's no way to map them to different classes from the same code, I see.

> That might be really easy, but not a high priority since all the K/E devices ship without a wifi/credentials sticker, so the API used by the cloud integration is probably the only way to get the MQTT credentials required to connect to it. But if anyone else can figure out a way, that'd be awesome! (I have a non-Formaldehyde 527K so maybe I can try to figure something out later)
> 

I do see value in keeping that manual flow working though, for if (or rather when) the cloud API shuts down or changes, it'll let you setup your fans anyway as long as you saved the credentials ahead of time. But fair enough, it's not urgent at all, just a nice to have.

> That said, it sounds like you have manual connection credentials already prepared somehow? I'm curious how you got your hands on that! If it turns out manual setup is a reasonable first-choice solution, we can definitely add it.
> 

Ah no sorry, I just use the get_devices.py script from the lib repo, which admittedly isn't a very user friendly solution. I'm not aware of a local way to grab those unfortunately, as you say it comes from the cloud even if only during setup so using cloud integration is fine.

> > Interestingly it's not pulling the same thing as my PRs on the old integration, it's pulling two indexes instead of VOC and No2
> 
> Funny enough, that's because the old integration was completely wrong in its assumptions about the data 🙃. There's a lot of discussion about it in #3 and #8 if you're interested! The short version is this: The sensors from the device itself aren't providing raw data in ppm or μg/m3 as previously supposed. It's actually just giving an index value that's (far as I can tell) proprietary to Dyson, and without knowing their conversion factors it's not possible to translate to a more meaningful measurement.
> 

Aha, I also suspected that. When I made those PRs I tried comparing them with other sensors I had (dyi, awair elements, airthings ..) and could never get them to agree, but since the app also shows different numbers at least some of the time I wasn't quite sure where the problem was. Sometimes even commercial sensors don't agree with each other ... Nice to know I'm not crazy.

> > for the formaldehyde it's just a number with no unit. I remember having to fix that up in the library in one of my PRs, probably the same issue here, from memory I think the sensor class was missing at least
> 
> We're still trying to figure out the raw data and understand what the base unit (or possible conversion factor) is for Formaldehyde. Weirdly enough, the app displays Formaldehyde (which is a VOC) in mg/m3, but for the general VOC sensor, it uses an index value. More discussion in #3 if you'd like to help us figure it out! Once we've got that, we'll add a sensor class and unit.

Alright apologies, I should have given that a read beforehand. Didn't realize this fork had moved that fast, nice !

I'm always happy to help but I don't want to over promise, just started a new job this week and may not have as much free time as I did recently 😆
