### ISSUE TITLE
Missing Formaldehyde devices on manual installation

### ISSUE THREAD

**Issue by emagnier** [libdyson-wg/ha-dyson#28]
I'm doing a manual installation.

I've a **Dyson Purifier Cool Formaldehyde**, but I do not see any Formaldehyde devices in the dropdown. Furthermore, some devices are listed twice in the list.

FYI, Formaldehyde devices were correctly output in the previous _shenxn_ repo.

![Screenshot 2023-06-05 at 12 55 40](https://github.com/libdyson-wg/ha-dyson/assets/1045997/2b9f1a25-d441-4f1e-afe9-fa8bc9dc6fba)

**Comment by dotvezz** [comment]
Hey @emagnier! This is sort of relevant to your issue, so I wanted to let you know there's a poll I opened over here: #49

**Comment by dotvezz** [comment]
Closing this one. Manual-only configuration of this generation of devices (HP07/09 and other devices released in late 2021 through 2022) is unfortunately still too messy due to model code conflicts. After merging the cloud features, the best way is to use a MyDyson account to automatically configure.

I _don't_ want to prevent discussion though. If you have any concerns or questions, feel free to follow up here!
