### ISSUE TITLE
Discussion section for questions

### ISSUE THREAD

**Issue by Anto79-ops** [libdyson-wg/ha-dyson#3]
Hi,

thanks for opening up an new Dyson repository. Any way to add a discussion section to this repository?

I'd like to ask a question if Dyson local does "I/O in the event loop"

For context, here is a [comment](https://github.com/home-assistant/core/issues/89047#issuecomment-1454860280)

I'm trying to find some demons in my HA instance and wanted to ask that question and if Dyson local does this, it would be good to fix that.

**Comment by Anto79-ops** [comment]
also, question #2 

Would it be possible to migrate to this new repository from the Shenxn one? Or do I have to remove the Shenxn one, and install this one?

I'm a little reluctant to remove the Shenxn one because I've heard of people having issues installing it again, but if one can confirm this is not the case anymore, that would be great!

**Comment by dotvezz** [comment]
> Would it be possible to migrate to this new repository from the Shenxn one? Or do I have to remove the Shenxn one, and install this one?

Yes! Here's the migration steps that have worked for me. I should add them to the readme.


### Experimental no-reconfiguration swap

I haven't tested this method very much, but in my experiments it seems possible to switch over with zero impact to your current integration configuration, entities/devices, or dashboards. I don't know what side-effects it may have though (leftover old config data might start causing issues or something - no guarantees).

1. Remove the ha-dyson and ha-dyson-cloud custom repositories from HACS
    - _Without_ removing the integrations themselves.
3. Add the new [ha-dyson](https://github.com/libdyson-wg/ha-dyson) and [ha-dyson-cloud](https://github.com/libdyson-wg/ha-dyson-cloud) custom repositories 
    - The ha-dyson-cloud repository is only necessary if you already use it, or are intending to use its features. It is not required, but currently, it makes setting up new devices like HP07 (527K) much simpler.
4. Update the ha-dyson and ha-dyson-cloud repositories using the HACS updater

### Proven some-reconfiguration swap

This is proven to work without any side effects. If you used the default IDs for the entities and devices, then you'll just need to re-configure the devices but your dashboards will not need updating.

0. Remove the Dyson Local and Dyson Cloud _integrations_ from your /config/integrations page.
1. Remove the Dyson Local and Dyson Cloud _integrations_ from your /hacs/integrations page.
2. Remove the dyson-ha and dyson-ha-cloud custom repositories from HACS
3. Add the new [dyson-ha](https://github.com/libdyson-wg/ha-dyson) and [dyson-ha-cloud](https://github.com/libdyson-wg/ha-dyson-cloud) custom repositories 
    - The libdyson-ha-cloud repository is only necessary if you already use it, or are intending to use its features. It is not required, but currently, it makes setting up new devices like HP07 (527K) much simpler.
4. Update the dyson-ha and dyson-ha-cloud repositories

**Comment by Anto79-ops** [comment]
Yes, thank you very much!

**Comment by GitPetri** [comment]
Tested the no-reconfiguration swap method, worked at least for me.

**Comment by Anto79-ops** [comment]
awesome. I just migrated using the "Proven some-reconfiguration swap". all my machines are working as they did.

You'll have to update/fix the HACS title page though, for some good PR :)

![image](https://user-images.githubusercontent.com/79593761/225707691-16facbc7-1398-4b6d-9291-c30dd56af217.png)

**Comment by khzd** [comment]
Hello
thanks to re activate this integration,:)  I was able to integrate my Dyson Pure Hot Cool today after years, everything is OK, integrated in local 
( NB the second region requested by get_devices.py is the code of the Contry ie DE, FR... )
If you need any help for testing...
Congratz  the dream team:)

**Comment by Anto79-ops** [comment]
Hello with the new version that just released 0.17.2, well I now be able to add my Dyson pure hot cool formaldehyde machine? I have it already added but it is added as only a pure hot cool so I don't have any formaldehyde functionality because when I click the formaldehyde machine and never wants to connect on setup. Thanks again for reviving this repo

**Comment by dotvezz** [comment]
Great question! 0.17.2 fixes cloud login issues. I'm working on an experimental recruit to fix formaldehyde and going to release it soon as 0.18.0.

**Comment by dotvezz** [comment]
I've released v0.18.0 of the dyson-local integration which now supports Formaldehyde devices!

One note, I've been testing with a _simulated_ device as my 527K happens to be the no-Formaldehyde version. Please feel free to install and test. There should be no breaking changes to dyson-local, but please let me know if you experience any problems.

cc: @Anto79-ops

**Comment by Anto79-ops** [comment]
Just updated and it works!

![Screenshot_20230430-195845.png](https://user-images.githubusercontent.com/79593761/235390088-ff77d1f3-5f62-4519-9211-d1d549eedfe6.png)

I didn't have to delete and add he device, it just showed up after restart!

**Comment by dotvezz** [comment]
Ah, I should have mentioned: You do _not_ need to delete and re-add! It detects whether or not it should provide that sensor when Home Assistant is loading the integration (like after a Home Assistant restart, etc) so you're good!

I wonder if it should have a unit like it has for NOX in your screenshot. Does the Dyson App display a particular unit with the Formaldehyde measurement?

**Comment by Anto79-ops** [comment]
Perfect it's all good I didn't delete anything. 

Yes, it should have units like this.
![Screenshot_20230430-200439.png](https://user-images.githubusercontent.com/79593761/235391218-7970e8d4-87ed-4a38-b669-626327dc7707.png)

But the unit is reporting is actually a little bit different than what the machine is reporting, for example 

![Screenshot_20230430-200734.png](https://user-images.githubusercontent.com/79593761/235391494-de1a40de-7d2c-432b-b84b-45c44660683c.png)

![Screenshot_20230430-200806.png](https://user-images.githubusercontent.com/79593761/235391503-865fdcdb-1edc-4dcf-839c-6225a57f1d13.png)


Also maybe the unit should be total increasing? When I click on it it doesn't show history plot, just colour coded numbers. 

![Screenshot_20230430-200947.png](https://user-images.githubusercontent.com/79593761/235391554-4cab9a03-b100-4662-9539-429857858a11.png)

But the number is updating and changing so there might be some conversion calculation that might need to be done.

**Comment by dotvezz** [comment]
Cool, that'll be an easy enough change! Thanks for the screenshots.

**Comment by dotvezz** [comment]
Okay Dyson was already kinda pissing me off with Formaldehyde devices sharing product codes with normal devices. But now the inconsistent units are even more annoying.

Why are they presenting the NOX measurement in **µ**g/m<sup>3</sup> but HCHO measurement in  **m**g/m<sup>3</sup>?? 5 µg/m<sup>3</sup> is the same as 0.005 µg/m<sup>3</sup>.

For my part, I think I'm just going to stick with µg/m<sup>3</sup> in the integration. I'll release a new change that improves the display and should add the correct units, should just take a moment. Let me know if anything's weird when it lands for you.

**Comment by Anto79-ops** [comment]
> Cool, that'll be an easy enough change! Thanks for the screenshots.
> 
> Edit: Oh interesting, yeah there may need to be some math for the sensor data. I'll dig into it a bit!

For sure. While you're at it,

I believe the NO2 and VOC units should be ppb. The Dyson app does some conversion to their 0 to 10 or 12 scale, but the machine outputs raw values I think. PM, temp, and humidity are correct of course. 

If you need help with the formaldehyde math, i might be able to extract that to a stats sensor or if you can fix the class so that it plots a history graph, I can try to compare with the Dyson app plots over 1 week or 2.

**Comment by dotvezz** [comment]
Yeah, I'd _really_ appreciate your help with the Formaldehyde math. I'll double-check the NOX and VOC calculations using my devices.

For the time being, I'll wait on the release that "fixes" the unit display - if I'm gonna correct something, I want to actually be _correct_.

If nothing else, now people can actually use their devices - we'll work on making the sensor data accurate next. Thanks for your help!

**Comment by dotvezz** [comment]
Okay, I couldn't sleep and went down a rabbit hold. Like you said, The raw sensor data seems to be what's coming over mqtt, and it is definitely not the same as what's coming from the app. On the one hand, I'll _always_ prefer raw data! On the other hand, I wish that we had a definitive answer as to what units that data will be in! Temp is reported in °K, which _feels_ like it would be a pretty unit to report. I've got a friend who works with industrial gear, maybe he'll be able to shine a light as to whether there's just an obvious standardization of units that we can assume the raw data is using.

Also, with this math I'm having to revisit a bunch of Chemistry I haven't thought about since university; getting molecular weight of things, finding the mass of 1m<sup>3</sup> of air at a given temperature and pressure. Fun stuff. Between that and looking at the Dyson app:

1. For NO<sub>2</sub> and VOC, annoyingly Dyson is doing some proprietary math to turn the sensors' raw data into their 0-9+ scale.
    - I'm betting it's ppb (as opposed to ppm) for NO<sub>2</sub> like you said - if it was ppm, wikipedia says I would be in "immediate danger" with my reading of 16 a few hours ago.
2. pm2.5 and pm10 are probably going through some proprietary math as well.
    - It's at least using an arbitrary (and proprietary) assumption about the composition of the particulate material being measured, and just using some constant value in the math. Without knowing information the composition, I'm pretty sure you can't actually get a molecular weight to convert to g/m<sup>3</sup>.
    - We can probably at least reverse-engineer the constant in this case. IF we do that, we can cross reference it against relevant ppm/ppb recommendations to whether it corresponds with those.
 3. Formaldehyde is also almost definitely ppb rather than ppm: 1ppm would be above [OSHA's exposure limits](https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1048).
 
It seems a safe bet that all the raw sensor data is in ppb. I don't know where Dyson is pulling atmospheric pressure from in order to convert it to µg/m<sup>3</sup> - it's a relatively cheap sensor to include with temperature, so it might be onboard? But it's definitely not sent over mqtt.

So I want to do this:

1. Confirm whether it's all ppb for the air quality sensors.
2. Update the HASS integration side to report the correct raw units, rather than doing the same kind of calculations that Dyson does.

**Comment by dotvezz** [comment]
Yeah, this has been an interesting exercise but I don't feel any closer to the base units for NO<sub>2</sub> or VOC at all. I was doing that exact math for NO<sub>2</sub> then realized that Dyson is giving us some unknown scale instead of µg/m<sup>3</sup>. I've been using [this calculator](https://aqicn.org/calculator/) to get an idea for what the raw numbers might correlate to but fell asleep before I wound up coming up with anything useful. I'll continue the search later today - this is gonna drive me crazy if I can't figure it out.

I'll also look into contacting Dyson directly to see if they're willing to share any info.

**Comment by dotvezz** [comment]
Got a bit more information to post here. I actually hopped onto a live chat on Dyson's website and asked directly. I'm not 100% confident in the information but hopefully it's better than nothing. The chat transcript is in [this gist](https://gist.github.com/dotvezz/646875c75e504dd801bcbd99f34f254b) if you're curious.

He seems pretty confident that NO<sub>2</sub>, VOC, and HCHO are all being measured and reported in ppb<sup>[1]</sup>. But like you've found for HCHO, there's not really a sane conversion factor I can work out that translates the measurements we're seeing into the numbers that the app is presenting.

For NO<sub>2</sub>, I'm having a hard time wrapping my head around the claim that it's actually in ppm even from the horse's mouth:

1. The idea that 0.028 ppm is supposedly an AQI of 1 in the app, since 0.028 ppm is about half of the limit for Nitrogen Dioxide (annual mean) as defined by [40 CFR § 50.11(c)](https://www.ecfr.gov/current/title-40/chapter-I/subchapter-C/part-50/section-50.11#p-50.11(c)).
2. Speaking of 40 CFR, looking at the chat, his explanation is suspiciously similar to a line from that exact reference. It looks like he might have just been copypasting and putting numbers where convenient. Note how 0.053ppm and 0.028ppm are **both** equal to 100 µg/m<sup>3</sup> in the two quotes (and almost identical verbiage):
     - From chat ([line 106](https://gist.github.com/dotvezz/646875c75e504dd801bcbd99f34f254b#file-gistfile1-txt-L106)):
       >  . . . 0.028 parts per million (ppm) (100 micrograms per cubic meter), annual arithmetic mean concentration.
     - From  [40 CFR § 50.11(c)](https://www.ecfr.gov/current/title-40/chapter-I/subchapter-C/part-50/section-50.11#p-50.11(c)):
       > . . . 0.053 parts per million (100 micrograms per cubic meter), annual arithmetic mean concentration.

For PM2.5 and PM10, I realized that the numbers I'm getting from MQTT actually match what the Dyson app is showing me. The app displays a µg/m<sup>3</sup> label with the graph. So I think it's actually reporting in µg/m<sup>3</sup> over mqtt? The inconsistency is kinda strange but I guess I can't complain about something being reasonably certain in these circumstances.

1: he said that 0028 is 0.028ppm, which is 28ppb, so I'm interpreting that as measurement in ppb.

**Comment by Anto79-ops** [comment]
just when I thought I had this figured out....lol

I can't make any sense from the units now. I will defer to your wisdom and knowledge on this :) But, what you say above, makes sense. It could very well all be ppb plus minus a multiple factor of 1000.

**Comment by dotvezz** [comment]
To be honest, I think I'm just going to try to work out the conversion factors and match what the Dyson app is presenting. Unless I find a way to talk to an actual Dyson engineer, I've given up on understanding what the heck the base units are supposed to be.

**Comment by dotvezz** [comment]
I'll continue the conversation about units in #4 in an attempt to keep things on topic :sweat_smile:.

**Comment by Anto79-ops** [comment]
I'm tried to dig into this by finding out what devices are actually in the unit but so far no luck

**Comment by Peronia** [comment]
Hi, I have a new Dyson Purifier Cool Autoreact TP7A, this one: https://www.dyson.de/raumklima/luftreiniger/purifier-cool-autoreact-tp7a/weiss-nickel
I added it to myDayon account and the cloud integration still says no devices found. So this device isn't supported?

**Comment by mundschenk-at** [comment]
> Hi, I have a new Dyson Purifier Cool Autoreact TP7A, this one: https://www.dyson.de/raumklima/luftreiniger/purifier-cool-autoreact-tp7a/weiss-nickel
> I added it to myDyson account and the cloud integration still says no devices found. So this device isn't supported?

Since the "autoreact" devices don't have app support, do they even have WiFi? I don't think these can be integrated (other than by cloning the remote control maybe) into a smart home system.

**Comment by Peronia** [comment]
No, they doesn't have wifi. But i don't know if they have MQTT.

**Comment by mundschenk-at** [comment]
> No, they doesn't have wifi. But i don't know if they have MQTT.

Without an underlying network connection, how should MQTT messages be sent?

**Comment by Peronia** [comment]
I have many devices without wifi but with some other support, so how should I answer this?

**Comment by mundschenk-at** [comment]
"Some other support" for what? 

MQTT needs a transport layer connection. That could be ethernet, WiFi, or even ZigBee, true. But those devices are Dyson's low cost line that doesn't include WiFi hardware - why on earth would you think they've added another networking subsystem that's not in the more expensive product line?

**Comment by GitPetri** [comment]
> Things change, so why not Dyson's devices? Anyway, is known what protocoll the remote control uses?

Dyson remotes use infrared. Controlling a non-networked device with Home Assistant can be done but requires additional hardware.
For example I have a couple of IR-remote devices (not Dyson thou) that are conrolled via Broadlink RM4 pro blaster and the HA [Broadlink integration](https://www.home-assistant.io/integrations/broadlink/) 
-

**Comment by Peronia** [comment]
Thanks @GitPetri, I have my Dysons (three) in seperate rooms, so I need 3 devices.. I'm not sure if i will set it up, we have mainly good air conditions here.
But the Dyson model which wifi costs 200€ more per unit, I am not willing to pay that.

**Comment by dotvezz** [comment]
Hey @Peronia! As far as I've I've been able to determine, the cheaper models without wifi don't have any connectivity at all.

You're right that the wifi tax for these devices is kinda crazy.

**Comment by catgirlkara** [comment]
If I were to manually enter device details in configuration.yaml what would that look like? The "manual" configuration isn't working for me.
![image](https://github.com/libdyson-wg/ha-dyson/assets/7052075/80238e1d-c5ed-48fc-9283-1df2d4137977)

**Comment by dotvezz** [comment]
> If I were to manually enter device details in configuration.yaml what would that look like?

@catgirlkara great question. This may be frustrating, but I don't have a clear answer for you using configuration.yaml. [Home Assistant has adopted a stance against supporting YAML configuration in integrations](https://developers.home-assistant.io/docs/configuration_yaml_index). If we're not able to solve your problem in another way, let's circle back to the yaml though.

I see you selected Purifier Hot+Cool. It's possible you're running into a quirk of Dyson devices starting with the that particular model. There's one more bit of information we'll need: the "device type." By any chance, did you use the get_devices.py script to get your credentials? If so, what was the "device type" result for your device? If it says "527E", the only fully supported way to set up your device is by linking your MyDyson account to the integration. Once you've configured your device itself. After initial discovery and setup, there's zero dependency on the MyDyson account so you can safely remove the MyDyson entry if you want to. 

<details>
<summary>Click here if you want more details as to <em>why</em> it works out this way</summary>

Each Dyson device has a product type that we need to know in order to connect to it. Before 2021, it was easy because each model had a specific code: the Pure Hot+Cool HP04 was 527, the Pure Cool TP04 was 438. But starting in 2021, the HP07 (Purifier Hot+Cool) and HP09 (Purifier Hot+Cool Formaldehyde) were released, and they both share the product codes 527K and 527E. Most or all of the devices released starting in 2021 have this issue, and we haven't found a reliable way to get the correct value other than using the Dyson App API.

Because the original code for this integration was written to depend on the "old" 1:1 relationships between model numbers and device types, despite the model showing up in that select menu, it only works if your device code is 527K. That's why the only fully supported way to add the Purifier Hot+Cool HP07 is by connecting a MyDyson account, which automatically fetches the device metadata from the API.
</details>

**Comment by dotvezz** [comment]
## Closing this thread to clean up the issues page. Feel free to post any new discussions in the Github [Discussions section](https://github.com/libdyson-wg/ha-dyson/discussions)!
