### ISSUE TITLE
Support for Speed entities/services

### ISSUE THREAD

**Issue by cpetzel** [libdyson-wg/ha-dyson#47]
Curious why Speed controls were removed in a [previous commit](https://github.com/libdyson-wg/ha-dyson/commit/0f1842a4043b79ed248f1cacb3a8f1a5fd6d7dd3#diff-5ec80f68f01807115128be925aa590a58930008cc1fe59ccc6e9610c917fc6f3L11)? 

Would it be possible to add back in support for displaying the current speed as an entity, and exposing a service to set the speed? 

(TP04)

**Comment by dotvezz** [comment]
> Curious why Speed controls were removed in a [previous commit](https://github.com/libdyson-wg/ha-dyson/commit/0f1842a4043b79ed248f1cacb3a8f1a5fd6d7dd3#diff-5ec80f68f01807115128be925aa590a58930008cc1fe59ccc6e9610c917fc6f3L11)?

That's a really great question. I wish I knew the answer, but that was done by Shen way before I adopted the project. It sure seems weird though.

> Would it be possible to add back in support for displaying the current speed as an entity, and exposing a service to set the speed?

Fret not, because it is currently supported! It was added back, perhaps somewhere around 49a7aa4240b49747b09a207cdc260cce32a151b8? Or maybe Shen's commit was just part of a refactor? I'm not entirely sure.

Anyway, a `fan` entity is exposed 's speed can be displayed and controlled.

![image](https://github.com/libdyson-wg/ha-dyson/assets/4571263/e1a48363-c129-4fff-929e-ef69ddd3897d)
![image](https://github.com/libdyson-wg/ha-dyson/assets/4571263/8fea3e48-ac07-429a-90fc-468140a6dc5f)

Let me know if you have any issues with it!

**Comment by mundschenk-at** [comment]
Home Assistant switched from named speeds to percentages for `Fan` entities. `Auto` mode was changed to a preset. These changes are not specific to the Dyson integration.

**Comment by cpetzel** [comment]
Wow! Total oversight on my part. I was searching through the entities list and debugging services and didn't see it. Now that I clicked on the device, I do see the same as your screenshot! 

I am able to use the "set speed percentage" service just fine!

Thanks for the info!

**Comment by dotvezz** [comment]
Glad you got it set up!

In Lovelace, it takes like 2 or 3 cards to cover all of the features of entities Some day I kinda want to make a custom card that fits the Dyson fans.
