### ISSUE TITLE
Dyson Purifier Humidify Cool Formaldehyde (358K) not supported

### ISSUE THREAD

**Issue by gonzolino69** [libdyson-wg/ha-dyson#8]
Please support Dyson Purifier Humidify Cool Formaldehyde 358K.

**Comment by KLucky13** [comment]
Just bought the Dyson hot + cool HP09 (formaldehyde model), so very iterested to see this one added

**Comment by zltn** [comment]
Having the same problem, I have and old Dyson pure cool (`438`) that I've been able to add locally. I also have a regular Purifier Humidify+Cool that I can't add. The `get_devices.py` out put is as follows:

```
Serial: K1D-US-XXXXXXXX
Name: Bedroom
Device Type: 358E
```

Is there already some workaround to add the device while it's fixed properly?

**Comment by dotvezz** [comment]
Well, v0.18.0 is released with support for all Formaldehyde devices! It uses a local interview process and does not require any cloud features (beyond the ones that Formaldehyde devices already require to setup initially).

One note, I've been testing with a _simulated_ device as my 527K happens to be the no-Formaldehyde version. Please feel free to install and test. There should be no breaking changes to dyson-local, but please let me know if you experience any problems.

cc: @zltn and @KLucky13

**Comment by dotvezz** [comment]
@BigThunderSR ahh, the upgrade to libdyson breaks the cloud integration eh? I'll get that resolved and post an updated version of the cloud integration today.

**Comment by dotvezz** [comment]
@BigThunderSR hmm, weirdly enough I don't actually see any references to `DysonPurifierHumidifyCool` in the cloud integration. I'm not sure why you're seeing that error, but I'll continue to look into it.

**Comment by dotvezz** [comment]
Just to be safe, I just released [ha-dyson-cloud v0.18.0](https://github.com/libdyson-wg/ha-dyson-cloud/releases/tag/v0.18.0) and see if that fixes it. All it does is match the libdyson version with the local integration.

Let me know if that resolves it for you - also, out of curiousity, do you own the Dyson Purifier Humidify+Cool? Maybe that would explain why you're getting that error while I'm not?

**Comment by KLucky13** [comment]
I just installed the update and the Formaldehyde value showed up, I don't see any other issues since updating! If I notice anything else I will post it here.

**Comment by KLucky13** [comment]
@dotvezz I might have found something, the formaldehyde sensor "results" are showing as a status bar and not as a graph:

![image](https://user-images.githubusercontent.com/16277786/235666185-14a30e0a-1940-4d91-8867-954832b74608.png)

if you compare it with PM25 for example:

![image](https://user-images.githubusercontent.com/16277786/235666285-7f388e95-4a6e-43b3-a2cf-c243efc4c437.png)

**Comment by dotvezz** [comment]
Hey @KLucky13! 

For your first issue, that's because of [sensors.py:327-338](https://github.com/libdyson-wg/ha-dyson/blame/main/custom_components/dyson_local/sensor.py#L327-L338) not setting a state class for the sensor. I actually have a branch with that fixed, but I was _hoping_ to figure out the base units issue and merge them together (#4, with [lots of discussion here](https://github.com/libdyson-wg/ha-dyson/issues/3#issuecomment-1530215158)).

Alas, the units issue is more frustrating than expected so I'll go ahead and do a patch release that updates the measurement display.

For your second question, I _think_ that's just because of how Home Assistant handles climate entities. You can call the set_temperature service on the climate entity (https://www.home-assistant.io/integrations/climate/ for the official docs), but let me know if that doesn't work!

**Comment by Anto79-ops** [comment]
@KLucky13 I think @dotvezz needs to introduce the 

`state_class: measurement`

to the formaldehyde sensor so it plots a history chart, but yeah, the units issue is frustrating even for a non-dev like me.

**Comment by gonzolino69** [comment]
Unfortunately, I still can't connect my device.

Serial: X6P-EU-XXXXXXXX
Name: living room
Device Type: 358K

**Comment by dotvezz** [comment]
@gonzolino69 I got an email that indicated you were still having problems, but looks like the comment is gone now. Were you able to get it up and working?

**Comment by dotvezz** [comment]
@KLucky13 we've got a new release that fixes the Formaldehyde display to a graph: https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.18.1

Note it also removes the µg/m³ unit label since @Anto79-ops realized that some conversion is apparently needed. We're trying to figure out the conversion math in #4 - if you can help by providing screenshots on that thread, it'd be amazing!

**Comment by gwigz** [comment]
Thanks for the great work, got this all setup with mine.

I don't have the option to change to toggle auto in Home/HomeKit. Is that a config issue, or something more to do with HomeKit or HASS Bridge?

**Comment by dotvezz** [comment]
@gwigz For your auto toggle in Home/Homekit - I dunno! Feel free to make a new issue where we can follow up on that though.
